### ISSUE TITLE
Unable to close the output pane

### ISSUE THREAD

**Issue by acdha** [natesilva/jshint-external.tmbundle#2]
I have TextMate configured to show preview output in a pane on the right. Using the keyboard shortcut to hide the HTML output does not hide the output but it does break something, freezing the current tab and making it impossible to edit – the cursor disappears and the editor will become unresponsive.

**Comment by natesilva** [comment]
Yikes. I use output in a new window and hadn’t seen that. I’ll take a look.

**Comment by natesilva** [comment]
Thank you.

**Comment by acdha** [comment]
Thanks for the rapid fix!
